baseURL: "https://jfeggio.github.io/"
languageCode: en-us
title: JFeggio
theme: PaperMod



params:
    assets:
        disableFingerprinting: true
    profileMode:
        enabled: true
        title: "Italian || BI & Systems Reporting Specialist at Henkel" # optional default will be site title
        subtitle: "Studying || Quantitative Methods for Data Analysis in Organizations at the University of Buenos Aires (UBA)"
        description: "MBA Turin University"
        imageUrl: "https://raw.githubusercontent.com/jfeggio/jfeggio.github.io/master/profile_pic.png" # optional
        imageTitle: "Foto" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size   
        buttons:
           - name: "Things I worked on"
             url: "/tags"
          #  - name: Github
          #     url: "https://github.com/" 
    socialIcons:
       - name: linkedin
         url: 'https://www.linkedin.com/in/jessica-feggio/'
    hideFooter: true
    hideMeta: true
    label:
      iconHeight: 15
  



        
# params:
#   homeInfoParams:
#     Title: "Hello"
#     Content: "Welcome"
#   socialIcons:
#       - name: linkedin
#         url: 'https://www.linkedin.com/'
#   assets:
#     favicon: "<link / absolute url>"
#     favicon16x16:  "<link / absolute url>"
#     favicon32x32:  "<link / absolute url>"
#     apple_touch_icon:  "<link / absolute url>"
#     safari_pinned_tab:  "<link / absolute url>"
menu:
   main:
     - identifier: tags
       name: Tags
       url: /tags/
       weight: 30
     - identifier: categories
       name: Categories
       url: /categories/
       weight: 20
     - identifier: posts
       name: Posts
       url: /posts/
       weight: 10



    #  - identifier: about
    #    name: About me
    #    url: /aboutme/
    #    weight: 10
     

#       ##pre: <link rel="icon" href="/argentina.png">  
    